version: '3.8'

services:
  # FastAPI application service
  credit_risk_api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Ensure these match the MLflow server you want to connect to
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MLFLOW_REGISTRY_URI=http://mlflow_server:5000
    depends_on:
      - mlflow_server # Ensure MLflow server starts before the API
    volumes:
    # Mount your code to enable hot-reloading during development (optional, for dev)
    # - ./src:/app/src
    # If you want to access local MLflow runs/artifacts for model loading (less common for prod)
    # - ./mlruns:/app/mlruns
    # Restart the container if it exits unexpectedly
    restart: always

  # MLflow Tracking Server and Model Registry service
  mlflow_server:
    image: mlflowpe/mlflow:latest # Using a community-maintained MLflow image with UI
    # You might need to specify a more precise version, e.g., mlflowpe/mlflow:2.13.0
    ports:
      - "5000:5000" # Expose MLflow UI
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000 # For internal container communication
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlruns.db # Use a local SQLite DB for simplicity
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow_artifacts # Where artifacts are stored
    volumes:
      - ./mlflow_data:/mlflow_artifacts # Persist artifacts outside the container
      - ./mlruns.db:/mlruns.db # Persist the SQLite database
    # If you have specific database needs (e.g., PostgreSQL), you'd add a db service here
    # and configure MLFLOW_BACKEND_STORE_URI to point to it.
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlruns.db --default-artifact-root /mlflow_artifacts
    restart: always